[package]
name = "ruscv-vector-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
simplelog = "0.12"
goblin = "0.10"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"